
<%@page import="java.io.*"%>
<%@page import="javax.servlet.*"%>
<%@page import="javax.servlet.http.*"%>
<%@page import="java.sql.*"%>

<%
String title = "Kobay_Exco_Paper_Form";
String columns = "RN,REVS,SUBJ,ON,CMPNYSLKOBAYSLBWESLKOBAY_GSLLODGE18SLLD_GLOBALSLPMISLKOBAY_UASLPPCSL,RMKS,CTGYSLPuchase_DisposalSLDividend_DeclarationSL";
%>

<!DOCTYPE html><html lang="en-US"><head><title>Drag & Drop Bootstrap Form Builder</title><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1" /><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" ><link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"><link rel="stylesheet" href="css/form_builder.css"/><style>body { background-color: #fafafa; }</style></head><body><div class="form_builder" style="margin-top: 25px"><div class="col"><div class="form-group"><label class="control-label form-control-lg">Kobay_Exco_Paper_Form</label></div></div><form action="../updatedb.jsp"><div  class="col-md-4"><div class="form-row"><div class="col"><div class="form-group"><label class="control-label">Reference Number</label><input type="number" name="RN" placeholder="" class="form-control" /></div></div><div class="col"><div class="form-group"><label class="control-label">Revision</label><input type="text" name="REVS" placeholder="" class="form-control" /></div></div></div><div class="form-row"><div class="col"><div class="form-group"><label class="control-label">Subject</label><input type="text" name="SUBJ" placeholder="" class="form-control" /></div></div><div class="col"><div class="form-group"><label class="control-label">Originator Name</label><input type="text" name="ON" placeholder="" class="form-control" /></div></div></div><div class="form-row"><div class="col"><div class="form-group"><label class="control-label">Company</label><select class="form-control" name="CMPNY"><option value="KOBAY">KOBAY</option><option value="BWE">BWE</option><option value="KOBAY_G">KOBAY_G</option><option value="LODGE18">LODGE18</option><option value="LD_GLOBAL">LD_GLOBAL</option><option value="PMI">PMI</option><option value="KOBAY_UA">KOBAY_UA</option><option value="PPC">PPC</option></select></div></div><div class="col"><div class="form-group"><label class="control-label">Remarks</label><input type="text" name="RMKS" placeholder="" class="form-control" /></div></div></div><div class="form-row"><div class="col"><div class="form-group"><label class="control-label">Category</label><select class="form-control" name="CTGY"><option value="Puchase_Disposal">Puchase_Disposal</option><option value="Dividend_Declaration">Dividend_Declaration</option></select></div></div></div><input type="text" name="column" placeholder="" class="form-control" value="<%=columns%>" style="display:none" /><input type="text" name="title" placeholder="" class="form-control" value="<%=title%>" style="display:none" /><br></div><div class="col-md-4"><button type="submit" class="btn btn-primary pull-right">Submit</button></div></form></div></body></html>