
<%@page import="java.io.*"%>
<%@page import="javax.servlet.*"%>
<%@page import="javax.servlet.http.*"%>
<%@page import="java.sql.*"%>

<%
String title = "Testingpurpose";
String columns = "TST123";
String[] column1 = columns.split(",");
int columnslen = column1.length;int index = 0;int count = 1;%>

<!DOCTYPE html><html lang="en-US"><head><title>Drag & Drop Bootstrap Form Builder</title><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1" /><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" ><link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"><link rel="stylesheet" href="css/form_builder.css"/><style>body { background-color: #fafafa; }</style></head><body><div class="form_builder" style="margin-top: 25px"><div class="col"><div class="form-group"><label class="control-label form-control-lg">Testingpurpose</label></div></div><form action="../updatedb.jsp"><div  class="col-md-4"><div class="col"><div class="form-group"><label class="control-label">testing123</label><input type="text" name="TST123" placeholder="" class="form-control" /><div class="TST123"></div></div></div><input type="text" name="column" placeholder="" class="form-control" value="<%=columns%>" style="display:none" /><input type="text" name="title" placeholder="" class="form-control" value="<%=title%>" style="display:none" /><input type="number" id="count" name="count" placeholder="" class="form-control" value="<%=count%>" style="display:none" /><br></div><div class="col-md-4"><button type="submit" class="btn btn-primary pull-right">Submit</button><button type="button" class="btn btn-primary pull-right" id="addmore">Add More...</button></div></form></div><script src="https://code.jquery.com/jquery-3.2.1.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script><script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script><script>document.getElementById("addmore").onclick = function(){var count = parseInt(document.getElementById("count").value) + 1;document.getElementById("count").value = count;<%while(index < columnslen){%>var html = '<input type="text" name=' + "<%=column1[index]%>" + ' placeholder="" class="form-control" />';$('.' + "<%=column1[index]%>").before(html);<%index++;}%>};</script></body></html>