
<%@page import="java.io.*"%>
<%@page import="javax.servlet.*"%>
<%@page import="javax.servlet.http.*"%>
<%@page import="java.sql.*"%>

<%
String title = "User_Profile345";
String columns = "DOB,FNAME,LNAME,RCCBMalayCBChineseCBIndianCB";
%>

<!DOCTYPE html><html lang="en-US"><head><title>Drag & Drop Bootstrap Form Builder</title><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1" /><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous"><link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"><link rel="stylesheet" href="css/form_builder.css"/><style>body { background-color: #fafafa; }</style></head><body><div class="form_builder" style="margin-top: 25px"><div class="col-md-4"><div class="form-group"><label class="control-label form-control-lg">User_Profile345</label></div></div><form action="../updatedb.jsp"><div class="col-md-4"><div class="form-group"><label class="control-label">Date of Birth</label><input type="date" name="DOB" class="form-control" /></div></div><div class="col-md-4"><div class="form-group"><label class="control-label">First Name</label><input type="text" name="FNAME" placeholder="" class="form-control" /></div></div><div class="col-md-4"><div class="form-group"><label class="control-label">Last Name</label><input type="text" name="LNAME" placeholder="" class="form-control" /></div></div><div class="col-md-4"><div class="form-group"><label class="control-label">Race</label><div class="form-check"><label class="form-check-label"><input type="checkbox" class="form-check-input" name="Malay" value="Malay">Malay</label></div><div class="form-check"><label class="form-check-label"><input type="checkbox" class="form-check-input" name="Chinese" value="Chinese">Chinese</label></div><div class="form-check"><label class="form-check-label"><input type="checkbox" class="form-check-input" name="Indian" value="Indian">Indian</label></div></div></div><input type="text" name="column" placeholder="" class="form-control" value="<%=columns%>" style="display:none" /><input type="text" name="title" placeholder="" class="form-control" value="<%=title%>" style="display:none" /><br><div class="col-md-4"><button type="submit" class="btn btn-primary pull-right">Submit</button></div></form></div></body></html>